# Walrus portal configuration (testnet).
# Used by mysten/walrus-sites-server-portal Docker image.
#
# Ref: https://docs.wal.app/sites/portals/deploy-locally
enableBlocklist: false
enableAllowlist: false
landingPageOidB36: "1p3repujoigwcqrk0w4itsxm7hs7xjl4hwgt3t0szn6evad83q"
portalDomainNameLength: 21
originalPackageId: "0xf99aee9f21493e1590e7e5a9aea6f343a1f381031a04a732724871fc294be799"
suinsClientNetwork: "testnet"
bringYourOwnDomain: false
idleTimeoutS: 52
idleTimeoutMaxS: 100
aggregatorTimeoutMs: 10000
rpcRequestTimeoutMs: 7000
rpcUrlList:
  - url: https://fullnode.testnet.sui.io
    retries: 2
    metric: 100
aggregatorUrlList:
  - url: https://aggregator.walrus-testnet.walrus.space
    retries: 3
    metric: 100
