#!/usr/bin/env bash
# deploy-vps.sh — One-command Cortex deployment on a fresh Ubuntu VPS.
#
# This script:
#   1. Installs Docker + Compose plugin if missing
#   2. Clones the repo (or uses current directory if already inside)
#   3. Prompts for .env values
#   4. Builds + starts the dev container
#   5. Prints next-step instructions for interactive bootstrap
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/<user>/cortex/main/scripts/deploy-vps.sh | bash
#   OR
#   git clone <repo> && cd cortex && bash scripts/deploy-vps.sh
#
# Tested on: Ubuntu 22.04 / 24.04
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

_log()  { echo -e "${CYAN}[deploy]${NC} $*"; }
_ok()   { echo -e "${GREEN}[  ok  ]${NC} $*"; }
_warn() { echo -e "${YELLOW}[ warn ]${NC} $*"; }
_err()  { echo -e "${RED}[ERROR ]${NC} $*"; }
_bold() { echo -e "${BOLD}$*${NC}"; }

# ── helpers ────────────────────────────────────────────────────────────

_confirm() {
    local prompt="$1"
    local default="${2:-n}"
    local yn
    read -r -p "$(echo -e "${CYAN}[deploy]${NC} ${prompt} [y/N] ")" yn
    yn="${yn:-$default}"
    case "$yn" in
        [Yy]*) return 0 ;;
        *) return 1 ;;
    esac
}

_has_cmd() { command -v "$1" >/dev/null 2>&1; }

# ── banner ─────────────────────────────────────────────────────────────

echo ""
_bold "======================================================"
_bold "  Cortex VPS Deployment"
_bold "  Sui Overflow 2026 — Walrus Track"
_bold "======================================================"
echo ""

# ── detect project root ────────────────────────────────────────────────

if [ -f "docker-compose.yml" ] && [ -f "CLAUDE.md" ]; then
    PROJECT_DIR="$(pwd)"
    _ok "Already inside Cortex repo: $PROJECT_DIR"
else
    REPO_URL="${CORTEX_REPO_URL:-https://github.com/<your-org>/cortex.git}"
    PROJECT_DIR="$HOME/cortex"
    if [ -d "$PROJECT_DIR" ]; then
        _warn "$PROJECT_DIR already exists — using existing clone"
    else
        _log "Cloning cortex..."
        git clone "$REPO_URL" "$PROJECT_DIR"
        _ok "Cloned to $PROJECT_DIR"
    fi
fi

cd "$PROJECT_DIR"
REQUIRED_FILES=("docker-compose.yml" "Dockerfile" "CLAUDE.md" "agent/requirements.txt")
for f in "${REQUIRED_FILES[@]}"; do
    if [ ! -f "$f" ]; then
        _err "Missing $f — is this a valid Cortex repo?"
        exit 1
    fi
done

# ── 1. install docker ──────────────────────────────────────────────────

if _has_cmd docker && _has_cmd docker-compose; then
    _ok "Docker already installed: $(docker --version)"
elif _has_cmd docker && docker compose version >/dev/null 2>&1; then
    _ok "Docker + Compose plugin already installed: $(docker --version)"
else
    _log "Installing Docker + Compose plugin..."
    curl -fsSL https://get.docker.com | sudo sh
    if ! grep -q docker /etc/group; then
        sudo groupadd docker 2>/dev/null || true
    fi
    sudo usermod -aG docker "$USER"
    _ok "Docker installed. You may need to re-login or run: newgrp docker"
    if ! docker ps >/dev/null 2>&1; then
        _warn "Docker socket not accessible. Try: newgrp docker (or logout + login), then re-run this script."
        echo "   sudo usermod -aG docker $USER && newgrp docker"
    fi
fi

# ── 2. configure .env ──────────────────────────────────────────────────

ENV_FILE="$PROJECT_DIR/.env"
if [ -f "$ENV_FILE" ] && grep -q 'LLM_API_KEY=.' "$ENV_FILE" 2>/dev/null; then
    _ok ".env already configured"
else
    _log "Setting up .env (LLM credentials)..."
    cp -n "$PROJECT_DIR/.env.example" "$ENV_FILE" 2>/dev/null || true

    echo ""
    echo "  Provide your LLM credentials (provider-agnostic, OpenAI-compatible endpoint)."
    echo "  Examples:"
    echo "    Google AI Studio:  base=https://generativelanguage.googleapis.com/v1beta/openai/  model=gemini-2.5-flash"
    echo "    OpenAI:            base=https://api.openai.com/v1                              model=gpt-4o-mini"
    echo "    MiniMax:           base=https://api.minimaxi.chat/v1                           model=MiniMax-M1"
    echo "    Local (Ollama):    base=http://localhost:11434/v1                              model=llama3"
    echo ""

    read -r -p "  LLM_BASE_URL: "  input_base
    read -r -p "  LLM_API_KEY:   "  input_key
    read -r -p "  LLM_MODEL:     "  input_model
    read -r -p "  LLM_GROUP_ID (optional, enter to skip): " input_group

    cat > "$ENV_FILE" <<EOF
# Generated by deploy-vps.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
LLM_BASE_URL=${input_base}
LLM_API_KEY=${input_key}
LLM_MODEL=${input_model}
LLM_GROUP_ID=${input_group}
EOF
    _ok ".env written"
fi

# ── 3. build container ─────────────────────────────────────────────────

_log "Building Docker image (this may take a few minutes)..."
if [ -n "${GITHUB_TOKEN:-}" ]; then
    _log "Using GITHUB_TOKEN to avoid API rate limits"
fi

docker compose build 2>&1 | tail -20
_ok "Image built: cortex-dev:latest"

# ── 4. start container ─────────────────────────────────────────────────

_log "Starting container..."
docker compose up -d
sleep 2

if docker compose ps | grep -q 'Up'; then
    _ok "Container is running: $(docker compose ps --format json | head -1)"
else
    _err "Container failed to start. Check: docker compose logs"
    exit 1
fi

# ── 5. verify tooling ──────────────────────────────────────────────────

_log "Verifying tooling inside container..."
docker compose exec -T cortex-dev bash -c '
set -e
echo "  sui:         $(sui --version 2>&1 || echo MISSING)"
echo "  walrus:      $(walrus --version 2>&1 || echo MISSING)"
echo "  site-builder: $(site-builder --version 2>&1 || echo MISSING)"
echo "  node:        $(node -v 2>&1 || echo MISSING)"
echo "  python3:     $(python3 --version 2>&1 || echo MISSING)"
'
_ok "Tooling verified"

# ── 6. next steps ──────────────────────────────────────────────────────

echo ""
_bold "======================================================"
_bold "  Deployment complete! Next steps:"
_bold "======================================================"
echo ""
echo "  Run the interactive bootstrap INSIDE the container:"
echo ""
echo "    docker compose exec -it cortex-dev bash"
echo "    bash /workspace/scripts/bootstrap-inside.sh"
echo ""
echo "  Or follow the manual steps in docs/DOCKER.md §4."
echo ""
echo "  After bootstrap, deploy the Walrus Site:"
echo ""
echo "    cd site && pnpm install && pnpm run build"
echo "    site-builder --context=testnet deploy --epochs max site/dist"
echo ""
echo "  Setup a cron job to extend blob epochs weekly:"
echo ""
echo "    crontab -e"
echo "    # Add: 0 8 * * 1 cd $PROJECT_DIR && docker compose exec -T cortex-dev bash /workspace/scripts/extend_blobs.sh"
echo ""
_bold "======================================================"
echo ""
_ok "Done. Happy hacking!"
